# Generated by Django 4.0.5 on 2022-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('img', models.CharField(max_length=255, verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('cast', models.CharField(max_length=255, verbose_name='Cast')),
                ('generes', models.CharField(max_length=255, verbose_name='Generes')),
                ('release_year', models.CharField(max_length=8, verbose_name='ReleaseYear')),
                ('country', models.CharField(max_length=128, verbose_name='country')),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('thumbnail', models.CharField(max_length=255, verbose_name='Thumbnail')),
            ],
        ),
    ]
